### ISSUE TITLE
Handling of single-band reference volumes and functional phase data

### ISSUE THREAD

**Issue by tsalo** [ReproNim/reproin#39]
I am attempting to organize a new pilot to match ReproIn convention. The pilot uses the CMRR multi band EPI sequence with multiple echoes, magnitude/phase reconstruction, and single-band reference volumes. Currently, I do not have any data acquired after renaming the protocol to follow ReproIn, but I do have some data using the same sequence that I coerced to match ReproIn after the fact (i.e., I loaded the dicoms, replaced the SeriesDescription and ProtocolName fields with appropriate ReproIn names, and saved them back out to a test directory). However, when running heudiconv on the reorganized dicoms using the ReproIn heuristic, there were some problems:
1. The phase data were converted to nifti, but saved as `_bold` instead of `_phase`, so it thinks they're magnitude (BOLD) data.
2. The actual BOLD data were not converted. I'm guessing that these runs were flagged as duplicates.
3. The single-band reference volumes also appear to have been flagged as duplicates of the BOLD data (actually the phase data). 
4. Only one "duplicate" scan was written out. It is one volume so I think it's the first echo's single-band reference image. Soon after heudiconv raised an error:
> RuntimeError: was asked to copy /tmp/dcm2niixtgxgf17z/convert/outputs/sub-reproin/func/sub-reproin_task-localizerDetection_run-01_bold__dup-01_e1_ph.nii.gz but destination already exists: /outputs/sub-reproin/func/sub-reproin_task-localizerDetection_run-01_echo-1_bold__dup-01.nii.gz

I can't share the raw data for this pilot participant, but I did recently share some phantom dicoms with the same sequence that could be converted to ReproIn-compatibility and should exhibit the same problems. [Here](http://datasets.datalad.org/?dir=/dicoms/salo/MEEPI) is the link to those dicoms. If there's anything I can do to help, please let me know.

**Comment by tsalo** [comment]
I think the problem can be resolved by adding more logic to the `seqtype_label` determination for func scans [here](https://github.com/tsalo/heudiconv/blob/95e35632cfabdf8046e67eb8ad8928cfc3165514/heudiconv/heuristics/reproin.py#L542-L553), like so:

```python
if seqtype == 'func' and not seqtype_label:
    if s.series_description.endswith('_SBRef'):
        seqtype_label = 'sbref'
    elif '_pace_' in series_spec:
        seqtype_label = 'pace'  # or should it be part of seq-
    elif 'P' in s.image_type:
        seqtype_label = 'phase'
    elif 'M' in s.image_type:
        seqtype_label = 'bold'
    else:
        # assume bold by default
        seqtype_label = 'bold'
```

At least in the CMRR sequence, single-band reference images have the same ProtocolName as the multi-band runs, but have `_SBRef` appended to the SeriesDescription and the DICOM folder. I don't know how sequence-specific this pattern is, though.

As far as functional phase data, the only difference I'm aware of in the DICOM headers is that the magnitude data have 'M' as one of the values in the `ImageType` tuple and phase data have 'P' in the same spot.

**Comment by yarikoptic** [comment]
Thank you! I will try to get a look within few days, please feel welcome to propose a PR for your change against heudiconv

**Comment by tsalo** [comment]
Thanks. I've opened https://github.com/nipy/heudiconv/pull/387 with my proposed changes.
