### ISSUE TITLE
Naming convention for acquisition with decimal value

### ISSUE THREAD

**Issue by dlevitas** [ReproNim/reproin#45]
I want to name an T1w anatomical acquisition with the resolution specified in the SeriesDescription. Would ```anat-T1w_acq-0.8mm```  be inappropriate due to the decimal, or is this fine by ReproIn standards? If not, is there some convention for SeriesDescription names which includes decimal values?

Thanks!

**Comment by yarikoptic** [comment]
yeah, unfortunately `.` is not allowed in BIDS.  You could use those on the scanner console, but then all `.` would be replaced with `X` (IIRC). So may be start with some other convention, e.g. `anat-T1w_acq-0p8mm` or `anat-T1w_acq-08mm`?  Anyways, `acq-` values are nohow treated/parsed, and actual resolution should be taken from data files.

**Comment by dlevitas** [comment]
Thanks for the clarification, I figured the decimal would be a problem. In that case then, I'll likely use your ```anat-T1w_acq-0p8mm``` suggestion moving forward. I'd like to have the SeriesDescription state what the resolution *should* be, but will compare it against the data files themselves.
