### ISSUE TITLE
Handling re-run fmap acquisitions

### ISSUE THREAD

**Issue by dlevitas** [ReproNim/reproin#46]
The walkthrough states that for interrupted acquisitions, all that needs to be done is to select "Repeat" and ReproIn will add a ```_dupX``` to the non-last acquisition(s). I'm curious though how to handle a situation where a participant exits and then re-enters the scanner in a single session, and the fmaps need to be re-run without marking some as duplicates? This is my thought process, but I wanted to see if this is correct in the ReproIn context:

the localizer and spin-echo field maps are labelled:
```
anat-scout_ses-01
fmap_dir_AP_run-1
fmap_dir-PA_run-1
```

During the middle of the scan session, the participant exits the scanner to use the restroom and then returns. Since the localizer and fmaps need to be re-run, would these scans need to be copied and re-labelled as such?

```
anat-scout_ses-01
fmap_dir-AP_run-2
fmap_dir-PA_run-2
```

**Comment by yarikoptic** [comment]
`_run` might be a bit odd since original one already would not have it, right?  I would have probably I would have just added into the copy `_acq-afterexit` or alike.  That would keep original `fmap` consistent across subjects, and only for some it would have this new one and a proper IntendedFor relationship added to .json (manually ATM) to bind that new fmap with corresponding seqences

**Comment by dlevitas** [comment]
So you recommend this before

```
anat-scout_ses-01
fmap_dir-AP
fmap_dir-PA
```

and after

```
anat-scout_ses-01
fmap_dir-AP_acq-afterexit
fmap_dir-PA_acq-afterexit
```

My only thought for using  ```_run-``` would be that the run identifier would be consistent across the entire study, even if only one pair of spin-echo field maps were needed for the majority of participants (and session). In other words, ```_run-1``` would simply be part of the fmap protocol naming, since run is an optional field. I realize the run identifier may be too redundant, but I'm open to either option so long as it's acceptable by ReproIn

**Comment by yarikoptic** [comment]
yeah, `_run-1` (although not strictly needed) should be ok as well.  ReproIn would not care and AFAIK bids validator would not either.  It would also open possibility for `_run-3` happen things go really "odd" ;)
