### ISSUE TITLE
ImportError: cannot import name 'TraitType'

### ISSUE THREAD

**Issue by dlevitas** [ReproNim/reproin#47]
I'm getting this error when running ```heudiconv -f reproin --bids --datalad -o $bids_root_dir --files dicom_dir```, which is:

```ImportError: cannot import name 'TraitType' from 'traits.trait_handlers' (/N/u/dlevitas/Carbonate/.local/lib/python3.7/site-packages/traits/trait_handlers.py)```

 I have ```git-annex```, ```datalad```, and ```heudiconv``` installed and in my $PATH

I think it's related this [nipype issue](https://github.com/nipy/nipype/issues/3157)

**Comment by dlevitas** [comment]
The commit fix in the nipype does indeed resolve the issue. I'm unable to submit a PR however because I don't see where on the github repo the necessary code is.

**Comment by yarikoptic** [comment]
try "search" -- I love it ;) (I am just semi-partially joking, I do frequently search for snippets of code here or https://codesearch.debian.net/ to determine the provenance of the code)

if you are talking about nipype -- should be here https://github.com/nipy/nipype/  . which version of `nipype` and `traits` do you have?

**Comment by dlevitas** [comment]
Ah okay, my nipype version was a bit old (1.3.2). Updating to 1.6.0 works!
