### ISSUE TITLE
Multiple Names/Words in Tree Setup

### ISSUE THREAD

**Issue by jmatthews-rotman** [ReproNim/reproin#55]
Question about the naming in the tree setup. Is there a convention for listing e.g. multiple PI's or Experimenters in the Region Name, perhaps separating them with dashes? Or is best practice to ID primary candidates for each, and edit the rest into the BIDS structure manually? Similarly, is there a convention if wanting to use a Project Name with multiple words in the Exam Name, or should we be creating single word short titles or using camelCase?

**Comment by yarikoptic** [comment]
> Question about the naming in the tree setup. Is there a convention for listing e.g. multiple PI's or Experimenters in the Region Name, perhaps separating them with dashes? 

Haven't heard about any. So I guess it is up to you - could always be "combined"

> Or is best practice to ID primary candidates for each, and edit the rest into the BIDS structure manually? 

Up to you really

> Similarly, is there a convention if wanting to use a Project Name with multiple words in the Exam Name, or should we be creating single word short titles or using camelCase?

yeah, people combine multiple (just 2-3) words in camelCase or relyingonhumanbrainparsing.

Not sure if helps ;) but all of the tree naming convention is quite flexible and logic for "splitting" is https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/reproin.py#L725 , so "fit your needs" ;)
