### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/reproin#70]
for example:

Reproducibility
Reexection
ReproLake
ReproPond
ReproCenter

add more comments!

**Comment by yarikoptic** [comment]
add where? not sure what is the purpose/point.  May be if you compose it as a PR , it would be easier to grasp the idea here

**Comment by asmacdo** [comment]
A glossary was brought up in the website subcommittee meeting. 

I think whatever the website ends up being, we will have lots of words that need definitions.

this issue is just placeholder to  track things that might benefit from being defined

**Comment by asmacdo** [comment]
...intended for a different repo. Your answer makes so much more sense now ;)
